In [26]:
from keras.models import load_model
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np
import tensorflow as tf

In [27]:
model = load_model('trained_model.h5')

In [28]:
img = tf.keras.utils.load_img('chest_xray//val//PNEUMONIA//person1946_bacteria_4875.jpeg', target_size=(64,64))

In [29]:
x = tf.keras.preprocessing.image.img_to_array(img)
print(x[0])
x = np.expand_dims(x, axis = 0)
img_data = preprocess_input(x)

[[  2.   2.   2.]
 [  1.   1.   1.]
 [  0.   0.   0.]
 [ 11.  11.  11.]
 [  1.   1.   1.]
 [ 10.  10.  10.]
 [ 15.  15.  15.]
 [ 13.  13.  13.]
 [254. 254. 254.]
 [ 19.  19.  19.]
 [ 43.  43.  43.]
 [ 76.  76.  76.]
 [105. 105. 105.]
 [144. 144. 144.]
 [159. 159. 159.]
 [163. 163. 163.]
 [181. 181. 181.]
 [161. 161. 161.]
 [172. 172. 172.]
 [165. 165. 165.]
 [158. 158. 158.]
 [164. 164. 164.]
 [162. 162. 162.]
 [160. 160. 160.]
 [170. 170. 170.]
 [165. 165. 165.]
 [163. 163. 163.]
 [156. 156. 156.]
 [152. 152. 152.]
 [147. 147. 147.]
 [149. 149. 149.]
 [137. 137. 137.]
 [129. 129. 129.]
 [121. 121. 121.]
 [104. 104. 104.]
 [ 76.  76.  76.]
 [ 72.  72.  72.]
 [ 71.  71.  71.]
 [ 66.  66.  66.]
 [ 62.  62.  62.]
 [ 58.  58.  58.]
 [ 57.  57.  57.]
 [ 49.  49.  49.]
 [ 41.  41.  41.]
 [ 50.  50.  50.]
 [ 44.  44.  44.]
 [ 43.  43.  43.]
 [ 44.  44.  44.]
 [ 39.  39.  39.]
 [ 34.  34.  34.]
 [ 37.  37.  37.]
 [ 43.  43.  43.]
 [ 46.  46.  46.]
 [ 40.  40.  40.]
 [ 39.  39.  39.]
 [ 37.  37

In [30]:
classes = model.predict(img_data)
classes

1/1 [==============================] - 0s 113ms/step


array([[1.]], dtype=float32)

0 is NORMAL IMAGE
1 is PNEUMONIA IMAGE

In [31]:
if(classes) == 1:
    print("Pneuomina")
else:
    print("Normal")

Pneuomina
